# YRWA Time Series Modeling & Forecasting


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(forecast)
library(Kendall)
library(tseries)
library(tidyverse)
library(readxl)
library(dplyr)
library(cowplot)
library(lubridate)
library(ggplot2)
library(smooth)
library(zoo)
library(kableExtra)
library(tidyr)

```

```{r}
# read warbler csv
warbler_daily <- read.csv("./Data/Cleaned_bySpecies/Warbler_Daily.csv")

head(warbler_daily)
```

```{r}
# filter observation from 2015-1-1 to 2025-12-31
warbler_daily_2 <- warbler_daily %>%
  filter(date >= as.Date("2015-01-01") &
         date <= as.Date("2025-12-31"))

str(warbler_daily_2)
```

```{r}
# convert to msts

warbler_ts <- msts(
  warbler_daily_2$sum_obs,
  seasonal.periods = c(7, 365.25)
)
```

```{r}
#ts plot
autoplot(warbler_ts) +
  labs(title = "Yellow-rumped Warbler Observations Counts by Day (2015–2025)",
       y = "Observation Count")
```

```{r}
# decomposed

warbler_ts_decomp <- decompose(warbler_ts)

autoplot(warbler_ts_decomp)
```

```{r}
# mstl
warbler_ts_mstl <- mstl(warbler_ts)

autoplot(warbler_ts_mstl)
```


```{r}
# initial acf & pacf
Acf(warbler_ts, lag.max = 400)
Pacf(warbler_ts, lag.max = 400)
```

```{r}
# arima + fourier model
arima_fourier_fit_34 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(3, 4))
)

summary(arima_fourier_fit_34)
checkresiduals(arima_fourier_fit_34)
```

```{r}
# model comparision
fit_26 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(2, 6))
)

fit_38 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(3, 8))
)

fit_310 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(3, 10))
)

fit_312 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(3, 12))
)

fit_314 <- auto.arima(
  warbler_ts,
  seasonal = FALSE,
  xreg = fourier(warbler_ts, K = c(3, 14))
)

model_compare <- data.frame(
  model = c("K=c(2,6)", "K=c(3,4)", "K=c(3,8)", "K=c(3,10)", "K=c(3,12)", "K=c(3,14)"),
  AIC = c(fit_26$aic, arima_fourier_fit_34$aic, fit_38$aic, fit_310$aic, fit_312$aic, fit_314$aic),
  AICc = c( fit_26$aicc, arima_fourier_fit_34$aicc, fit_38$aicc, fit_310$aicc, fit_312$aicc, fit_314$aicc),
  BIC = c(fit_26$bic, arima_fourier_fit_34$bic, fit_38$bic, fit_310$bic, fit_312$bic, fit_314$bic)
)

model_compare <- model_compare[order(model_compare$AICc), ]
print(model_compare)

```

```{r}
checkresiduals(fit_312)
```
> Convert to weekly data?
